/**
 * Created by nburk on 10/03/17.
 */

export const TEST_WITH_NEW_CUSTOMER = false
export const FREECOM_CUSTOMER_ID_KEY = 'FREECOM_CUSTOMER_ID'
export const FREECOM_CUSTOMER_NAME_KEY = 'FREECOM_CUSTOMER_NAME'

export const FREECOM_AUTH_TOKEN_KEY = 'FREECOM_AUTH_TOKEN'
export const FREECOM_CUSTOMER_SECRET_KEY = 'FREECOM_CUSTOMER_SECRET'

export const MAX_USERNAME_LENGTH = 17